### ISSUE TITLE
Show all devices of certain kind?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [xBourner/status-card#27]
Hi, 

I love the status-card, but I can't seem to find to show all devices of given kind. Only those which are open or active in some way?

![Image](https://github.com/user-attachments/assets/fa733e32-ad0d-4b83-b36d-2dc6e6abddbd)

Basically when it says 2 out 6 locks, I can only see 2 entities there. Would it be possible to show all of them? Like I would like an easy way to control all blinds from single place using status-card?

Przemek

**Comment by xBourner** [comment]
I like the idea and i will 100% implement this. I will think about how i will do this.

My first thought is a toggle when you open the popup to toggle between all entities and "on" or off "state" entities. 
Default behaviour would be to show only the "on" entities. If you enable the total entities and it shows 2/6 locks open it should show every entity (on and off).

I don't know if i am able to have such a switch in the popup (this probably wont be a permanent setting) or if the switch is in the default config. 

Let me think about that some days and i hope i will finish this next week.

**Comment by PrzemyslawKlys** [comment]
Great! The problem that I also see is that not everything that is open is bad thing, and sometimes closed is bad thing depending on how you see things.

**Comment by xBourner** [comment]
I agree 100%. Also had the problem that I didn't see the entities I wanted to see. But never thought about implementing something like this.

I will do it for the domains that are available at the moment.

**Comment by PrzemyslawKlys** [comment]
One more thing regarding this - joined domains. For example shutters and blinds. They do the same thing, have same a actions, but are split into 2 categories... not terrible, but would be great if one could merge them somehow.

**Comment by xBourner** [comment]
regarding your last comment:

there wont be joined domains. some domains like switch, cover and binary_sensor kinda do all the same but for better visibility there are grouped by their device_class. with this you can see better which devices are on/open. i understand that sometimes you want to open/close all cover entities but i think the card is better when covers are grouped by device_class.

**Comment by xBourner** [comment]
Did you have the time to check the new toggle feature in the latest release?

There a three dots in the top right corner when you open the popup. Now there are two new features.

1. turn off all - will turn off all entities that are on (should work for most domains - I haven't tested all of them)
2. toggle entities - will toggle between entities that are in "on" state and every entity (on and off)

There is also a new toggle to permanently show all entities instead of just the "on" entities. This can be found in the editor under appearance tab.

**Comment by PrzemyslawKlys** [comment]
Nice, I saw the first option, but kind of ignored the 2nd option while looking at changelog. 

![Image](https://github.com/user-attachments/assets/664a997d-adfd-4f12-a7a1-54121adc5615)

![Image](https://github.com/user-attachments/assets/aff060c4-bee9-486f-91ad-8ba476fc2fdb)

The one thing that would probably be great to improve is to be able to hide rooms and just display the entities next to each other (retaining order of rooms tho, or alphabetical).

I can understand room split, but most of the time I put the name of room inside entity and I would rather see all entities then having to scroll. 

But it's already amazing!

**Comment by PrzemyslawKlys** [comment]
After playing with this a bit, it would be useful if one could decide whether to show all or just some per category. Like lights (i have lots), locks just a few. So sometimes it makes sense to show all locks, but not all lights. Also the right top corner for switch with `:` is a bit painful. Would be great if there could be a toggle that's easily accessible and visible.

**Comment by PrzemyslawKlys** [comment]
That's a good question. Mostly I would like to somehow choose which types get what. I guess one way to achieve it is to have Edit Content split into 3 sections "All", "Only on", "only off". Not sure if there are any other states that could be useful, but sometimes my Tahoma leaves some devices in "opening" state, but that's probably too much.

![Image](https://github.com/user-attachments/assets/07449465-d807-4071-826f-d03cbf6db86d)

The problem is tho, how to set up a proper order with 3 separate lines...

**Comment by xBourner** [comment]
sorry for the delay. i hadnt much time the last days. i like the idea of a seperation of "on" entities and "off" entities. now they should show up in the beginning but seperate lines could look good.

ive found some other issue with the popup and i will look into this at first but i will look if i can seperate the entities to have better visbility and usability. but im not sure at the moment if i will implement this. maybe i wont like it.

**Comment by xBourner** [comment]
are you happy with the latest sorting changes? can i close this?

**Comment by PrzemyslawKlys** [comment]
I actually have one more idea. Sorting by state, not by area where it makes sense. For example when going to sleep, checking if all lights are off or which lights are on still would make sense if they were closer to the top. Rather than per area.

Having said that i don't understand what is that?

<img width="387" alt="Image" src="https://github.com/user-attachments/assets/b91337bc-fbc0-49a7-b1af-7406d829e77b" />

And then for some reason my lights are completely ignored:

![Image](https://github.com/user-attachments/assets/6c39398c-24a5-44ca-8573-05459790af7f)

The yaml for this:

```
content:
  - lock
  - light
  - media_player
  - climate
  - Switch - switch
  - Switch - outlet
  - fan
  - remote
  - Cover - garage
  - Cover - gate
  - Cover - blind
  - Cover - awning
  - Cover - shutter
  - Binary Sensor - door
  - Binary Sensor - motion
  - Binary Sensor - occupancy
  - Binary Sensor - power
  - Binary Sensor - battery
  - Binary Sensor - battery_charging
  - Binary Sensor - running
  - Binary Sensor - heat
  - Binary Sensor - moisture
  - Binary Sensor - connectivity
  - Binary Sensor - problem
  - Binary Sensor - safety
  - Binary Sensor - update
  - update
  - device_tracker
  - input_boolean
  - calendar
  - Binary Sensor, Cover - window
type: custom:status-card
columns: 4
hide_person: false
list_mode: false
hide_content_name: false
customization: []
grid_options:
  columns: full
  rows: auto
square: true
show_total_entities: true
show_total_number: true
```
